### ISSUE TITLE
Wrong Result Computing general traces

### ISSUE THREAD

**Issue by ariosfukelman** [FormTracer/FormTracer#2]
While using FormTracer with a general group there seems to have problems while tracing expressions like Tr[T^a T^b T^c]. 

Following the the [color paper](https://www.nikhef.nl/~form/maindir/packages/color/color.pdf) we see at equation (42) that such traces are given in terms of symmetric invariant tensor, the Index of the representation and the structure constants. But if we compute: 

`DefineGroupTensors[{{GenericGroup, color, generalAdjDelta[a, b], generalStructureConstant[a, b, c], generalDeltaFund[i, j], generalGenerator[a, i, j]}]`

`FormTrace[generalGenerator[a,i,j] generalGenerator[b,j,k] generalGenerator[c,k,i]`

The result is
`grpvecxcR1[a] grpvecxcR1[b] grpvecxcR1[c]` 
That seems to correspond to the symmetric invariant tensor (by explicit computing it) and not the corresponding equation (42) of the color paper.

**Comment by antoncyrol** [comment]
Thanks for reporting this. The partial traces feature is not supported by the color package algorithm (and the whole feature should rather be seen as experimental). Of course, in any case FormTracer should not yield wrong results. 

FormTracer version 2.3.6 fixes this issue, please check!

Technical details:
The generic contraction algorithm from the color package has a procedure #simpli which is called by FormTracer. However #simpli assumes closed indices, which is not the case in the provided case and thus leads to wrong results (i.e. #simpli drops the missing term in  equation (42)). FormTracer v2.3.6 only calls #simpli if the PartialTraces feature is not used.

**Comment by ariosfukelman** [comment]
Thanks for the answer. For the three generators case it's working, but it fails at higher orders, for example while computing

`FormTrace[generalGenerator[a, i, j] generalGenerator[b, j, k] generalGenerator[c, k, l]generalGenerator[d, l, i]]`

Doesn't reproduce the following term in (42)!

**Comment by antoncyrol** [comment]
What do you get as a result?

**Comment by ariosfukelman** [comment]
I get
`1/3 I2Rc generalStructureConstant[a, d, adjcolorDummy1] generalStructureConstant[b, c, adjcolorDummy1] - 1/6 I2Rc generalStructureConstant[a, c, 
   adjcolorDummy1] generalStructureConstant[b, d, adjcolorDummy1] + 
 1/2 I generalStructureConstant[c, d, grpvecxcR1] grpvecxcR1[a] grpvecxcR1[b] + 
 1/2 I generalStructureConstant[a, b, grpvecxcR1] grpvecxcR1[c] grpvecxcR1[d] + grpvecxcR1[a] grpvecxcR1[b] grpvecxcR1[c] grpvecxcR1[d]`


While it should be
`grpvecxcR1[a] grpvecxcR1[b] grpvecxcR1[c] grpvecxcR1[d] + 1/2 I (grpvecxR1c[a]grpvecxcR1[d]grpvecxcR1[adjcolorDummy1]generalStructureConstant[b,c,adjcolorDummy1]-grpvecxR1c[b]grpvecxcR1[c]grpvecxcR1[adjcolorDummy1]generalStructureConstant[a,d,adjcolorDummy1]) +1/6 I2Rc (generalStructureConstant[a, d, adjcolorDummy1] generalStructureConstant[b, c, adjcolorDummy1]-generalStructureConstant[a, b, adjcolorDummy1] generalStructureConstant[c, d, adjcolorDummy1])`

**Comment by antoncyrol** [comment]
Okay, I see. I think both expressions are equivalent and thus correct, although the notation with grpvecxcR1 appearing in generalStructureConstant[a, b, grpvecxcR1] is non-standard (and perhaps special to the color package).

Hence, you need to interpret the result correspondingly or refrain from using the color package algorithm in combination with the partial traces features (and project in the standard manner).

I'm sorry, but FormTracer can't do better ... as it only uses the algorithm provided in the color package.

**Comment by ariosfukelman** [comment]
Okay, so 
`1/2 I generalStructureConstant[c, d, grpvecxcR1] grpvecxcR1[a] grpvecxcR1[b]` should be interpreted as i/2 f^{c d n} d^{abn} to match with the desired result. 

Nevertheless there seems to be a mismatch of a factor of 2 in the term corresponding to the Index since the output produces one with 1/3 and another with 1/6 while in the color paper both terms come with 1/6 or I'm missing something more?. 

Thank you very much for your insights!

**Comment by antoncyrol** [comment]
It seems as if you have overlooked the different indices in the two expressions. Just insert the Jacobi identity,
`f[a,c,n] f[b,d,n] = f[a,b,n] f[c,d,n] + f[b,c,n] f[a,d,n]`
into 
`1/3 I2Rc f[a,d,n] f[b,c,n] - 1/6 I2Rc f[a,c,n] f[b,d,n]`
and you get
`1/6 I2Rc (f[a,d,n] f[b,c,n] - f[a,b,n] f[c,d,n])`
as desired (where I used f=generalStructureConstant, adjcolorDummy1=n).
