### ISSUE TITLE
Mathematica 12 support

### ISSUE THREAD

**Issue by gothicVI** [FormTracer/FormTracer#3]
Hi,

it seems that FormTracer is broken in MATHEMATICA version 12. It seems that FORM cannot be located or called. I'm getting
```
    "FORM exited with error code 1."
    "FORM exited with error code 1."

    Line 1 -->
```
And the stack trace for the first error: `Message[FormTrace::formeexitcode, 1]`, and the second error: `Message[FormTrace::formerror, " \nLine 1 --> "]`, respectively.

Any way I can help debug this? The code runs fine using MATHEMATICA 11.3.

**Comment by antoncyrol** [comment]
1) Create a minimal working example if you haven't done so already.

2) Activate FormTracer's debugging mode by evaluating DebuggingMode[True]. FormTracer then saves (and keeps) the FORM files to the current working directory in the folder "FormTracerCache". Compare the files generated with Mathematica 11.3 and 12 and/or try to evaluate them manually with FORM.

I have no Mathematica licence any longer (and never had one for v12) ...

**Comment by gothicVI** [comment]
Thanks for your answer. I'm sticking to the example that comes with the program as a minimal working example, i.e.:
```
    formTracerInstalled = Quiet[Needs["FormTracer`"]];
    If[formTracerInstalled === $Failed,
     Import["https://raw.githubusercontent.com/FormTracer/FormTracer/master/src/FormTracerInstaller.m"]
     ]
    DebuggingMode[True]
    DefineGroupTensors[{
      {SUNfund(*group type*),
       {color(*name of group*), Nc(*dimension of representation*)
        (*(*more options for groups of type GenericGroup: *),
        cR(*quadratic casimir operator of representation*),
        NA(*dimension of adjoint representation*),
        cA(*quadratic casimir operator of adjoint representation*),
        I2R(*second order index of representation (normalisation)*)*)},
       \[Delta]A[a, b](*Kronecker delta in adjoint space*),
       f[a, b, c](*structure constants*),
       \[Delta]F[i, j](*Kronecker delta in representation space*),
       T[a, i, j](*generators of representation*)}
      }]

    FormTrace[f[a, b, c] f[a, c, b]]
```
which works fine for MATHEMATICA 11.3, resulting in
```
Time needed for converting input, extracting momenta and indices: 0.000857
Time needed for expansion and generation of FORM expressions: 0.010718
Time needed for string generation: 0.002706
Time needed by Form: 0.023751
Time needed to import the result: 0.004135
Nc-Nc^3
```
but fails in MATHEMATICA 12.0, resulting in
```
CreateDirectory::privv: Privilege violation for file or directory /FormTracerCache.
Time needed for converting input, extracting momenta and indices: 0.001477
Time needed for expansion and generation of FORM expressions: 0.041208
OpenWrite::noopen: Cannot open FormTracerCache/runform_2019-05-29-08-35-56.858191-f11.frm.
WriteString::strml: $Failed is not a string, stream, or list of strings and streams.
Close::stream: $Failed is not a string, SocketObject, InputStream[ ], or OutputStream[ ].
Time needed for string generation: 0.032501
FormTrace::formeexitcode: FORM exited with error code 1.
Time needed by Form: 0.030837
ImportFormResult::noformoutput: An unknown FORM error occured!
No FORM output was generated.
$Aborted
```
I'm not sure how and where exactly FormTracer tries to store the generated output for form but in my understanding, there might have been a change in either basepath or relative path between MATHEMATICA versions 11.3 and 12.0 leading to an attempt to write into a directory without access.

Also, I couldn't find a folder named `FormTracerCache`. Is it supposed to be in the notebook directory?

Have you been looking into the just freely released Wolfram engine ([https://www.wolfram.com/engine/](https://www.wolfram.com/engine/))?
That would give you a MATHEMATICA 12.0 kernel without the need to buy a license.

**Comment by antoncyrol** [comment]
The first line
`CreateDirectory::privv: Privilege violation for file or directory /FormTracerCache.`
tells you that CreateDirectory[] misses the privilege to create the directory "/FormTracerCache". Could you try setting the working directory explicitly such that you have access to it? E.g. 
`SetDirectory[NotebookDirectory[]]`
should do the job. Then FormTracerCache should be in your notebook directory.

**Comment by gothicVI** [comment]
Hi,

`SetDirectory[NotebookDirectory[]]` actually does the trick. Now the two outputs are the same and also all the generated files are the same.
Could this somehow be implemented as either default or do you have any idea why MATHEMATICA 12.0 no longer allows writing to directories MATHEMATICA 11.3 had no issues with?

Thanks a lot!

**Comment by antoncyrol** [comment]
It seem as if Mathematica 12 can write in all directories 11.3 can write in, but that for some reason in your case the working directory is the root directory "/" (where you obviously have no access as non-root user) and hence FormTracer tries to create the directory "/FormTracerCache". Check the working directory with "Directory[]".

However, back to your original problem: Is it still there?
If so, I am confused because the original error "FORM exited with error code 1." hints at a FORM (script) error, but you state that the FORM files are identical ... 
This would imply that there is a problem with the execution of FORM from Mathematica or, as the results file exist, with the import of the results. What OS are you using?

**Comment by gothicVI** [comment]
Hi,

simply running `Directory[]` in MATHEMATICA 12.0 returns my home directory (running Ubuntu 18.04LTS) as does MATHEMATICA 11.3.

The original problem is "solved" once I run `SetDirectory[NotebookDirectory[]]` but persists if I don't which is really strange, given that `Directory[]` returns the same path in both versions.
Anyhow, once I run said command both versions generate identical FORM files and run the MWE just fine.

So it has to be some (internal?) path changes in the transition MATHEMATICA 11.3 --> 12.0 that somehow change some default path used by FormTracer into something that is not writeable.

I hope that clarifies your confusion. Any other verbose tests I could run to debug?

**Comment by antoncyrol** [comment]
Glad to hear that it works with the directory set, but I still don't know how it comes ...

Could you evaluate $TemporaryDirectory in both versions? Because that is the folder in which FormTracer writes its temporary files if it is not in debugging mode.

**Comment by gothicVI** [comment]
Evaluating `$TemporaryDirectory` in MATHAMTAICA 11.3 and 12.0 returns `/tmp` in both versions.

EDIT: I can't tell what might have changed but I realized just now running the above MWE that MATHEMATICA 12.0 now also produces the correct output with and without:

- having `DebuggingMode[True]` in the code
- running `SetDirectory[NotebookDirectory[]]`

I'm honestly baffled by what's happening here. Anyhow, thanks a lot for taking the time to help to debug!
