### ISSUE TITLE
PartialTrace Bug

### ISSUE THREAD

**Issue by rosenblueh** [FormTracer/FormTracer#5]
There seems to be a minor bug in the experimental PartialTrace feature. If an expression only contains fundamental but no adjoint indices, the fundamental indices are converted to adjoint ones. Same with Dirac and Lorentz. This can be seen by executing
```
DefineLorentzTensors[deltaLorentz[mu, nu], vec[p, mu], sp[p, q], eps[], deltaDirac[i, j], gamma[mu, i, j], gamma5[i, j]];
DefineGroupTensors[{{SU2fundexplicit, color, deltaAdjCol[a, b], structureConstantCol[a, b, c], deltaFundCol[i, j], generatorCol[a, i, j]}}]
PartialTrace[True]
FormTrace[deltaFundCol[f1, f2]]
FormTrace[deltaDirac[i, j]]
```
which results for me in
```
deltaAdjCol[f1, f2]
deltaLorentz[i, j]
```

it doesn't happen when fundamental as well as adjoint indices are present in an expression.  Inspecting the generated FORM file with the debugging feature, the following combination of lines seems responsible (for the first case with color indices)

Lines 46-48:
```
*** color index sets
Set acIndices: ;
Set fcIndices: fc1,fc2;
```

Lines 101-102
```
id d_(ac1?acIndices,ac2?)=FTxdeltaAdj(color,ac1,ac2);
id d_(fc1?fcIndices,fc2?)=FTxdeltaFund(color,fc1,fc2);
```

where the empty set of acIndices seems to cause the error.

**Comment by antoncyrol** [comment]
Hi @dan-ros, thanks for your bug report and especially for pinpointing the error. I think it should be rather easy and quick to fix. I left physics some time ago and thus no longer have a valid Mathematica licence. Hence, I cannot fix it. My collaborators also left physics. Maybe @nstrodt still has a licence and is interested in fixing it? If not, I am more than happy to accept pull requests @dan-ros . Note, however, that FormTracer's install and update mechanism requires some special steps to work. I just added my [notes](https://github.com/FormTracer/FormTracer/blob/51142ee35e889e68ed64405232b8ce9308315a48/FormTracerVersioning.txt) on how to achieve this (I know, nowadays you would use Github release for this task).
