### ISSUE TITLE
Issue with Partial Traces

### ISSUE THREAD

**Issue by gpbrito** [FormTracer/FormTracer#7]
I found an issue with calculations involving traces with open indices associated with Spinors or "Group Tensors".

(For simplicity I will refer to the objects defined in "FormTracerShowcase.nb")

In the first case, the partial trace converts deltaDirac into deltaLorentz. In the case of "Group Tensors", the partial trace converts deltaFund into deltaAdj. I'm attaching here a snapshot with the two examples.

<img width="972" alt="Screenshot 2022-02-04 at 15 01 49" src="https://user-images.githubusercontent.com/99028514/152541713-8e02da5f-091b-49df-a57a-aee1991098fb.png">

In principle I have a solution for this in my own code, but I hope this information might be useful for the developers.

**Comment by antoncyrol** [comment]
This looks like a serious bug. Why did you @gpbrito close it? Even if it is not a bug, an explanation might be helpful for users encountering the same problem in the future.

**Comment by gpbrito** [comment]
Hi @antoncyrol,
I closed my post because right after posting the message I saw that the same question was discussed in another post about an year ago (https://github.com/FormTracer/FormTracer/issues/5). 
Also, the last update of the package already fixed this issue (https://github.com/FormTracer/FormTracer/blob/master/FormTracer.zip).
