### ISSUE TITLE
the calculation is different form Peskin Quantum field theory book

### ISSUE THREAD

**Issue by zhangzhihua125** [FormTracer/FormTracer#8]
FormTrace[
 gamma[mu, a, b] gamma[nu, b, c] gamma[rou, c, d] gamma[sigma, d, 
   e] gamma5[e, a] vec[p1, mu] vec[p2, nu] vec[p3, rou] vec[p4, 
   sigma]]

the result: 4 e_[p1, p2, p3, p4]

the book result
![formtracer](https://github.com/FormTracer/FormTracer/assets/171466119/80bce3d8-62d0-4cac-9923-14ec727cad38)

**Comment by vsht** [comment]
Not a FormTrace dev, but this is a matter of how one defines the trace
of 4 matrices and one g^5.

Cf.

<https://www.nikhef.nl/~form/maindir/documentation/reference/html/manual.html#x1-34500015>

It's related to the fact that FORM and most other similar tools
do not distinguish between lower and upper indices, which requires
some dedicated treatment of the eps tensor, especially when taking
the conjugate of the amplitude.







Am 02.06.24 um 05:57 schrieb zhangzhihua125:

**Comment by zhangzhihua125** [comment]
I have understood your comment. Thank you for your reply!
